version: '3.8'

services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
